<a href="https://colab.research.google.com/github/Blenkzx/LINGUAGENS-DE-PROGRAMA-O/blob/main/NumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Nível 1: Básico — Faturamento Semanal e Filtros

### Passo 1: Crie um array unidimensional `pecas_vendidas`.

In [2]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
display(pecas_vendidas)

array([150, 120,  90, 210, 300, 250, 180])

### Passo 2: Calcule o faturamento semanal, sabendo que o preço médio de cada peça é de R$ 50,00.

In [3]:
preco_peca = 50
faturamento_semanal = pecas_vendidas * preco_peca
display(faturamento_semanal)

array([ 7500,  6000,  4500, 10500, 15000, 12500,  9000])

### Passo 3: Identifique os dias de pico (vendas estritamente mais de 200 peças).

In [4]:
dias_pico_mascara = pecas_vendidas > 200
dias_pico = pecas_vendidas[dias_pico_mascara]
display(dias_pico_mascara)
display(f"Vendas nos dias de pico: {dias_pico}")

array([False, False, False,  True,  True,  True, False])

'Vendas nos dias de pico: [210 300 250]'

## Nível 2: Intermediário — Múltiplas Filiais e Falhas de Sistema

### Passo 1: Crie uma matriz 2D para vendas de três filiais.

In [5]:
vendas_filiais = np.array([
    [200, 220, np.nan, 250],  # Loja A
    [150, 180, 160, 190],   # Loja B
    [300, 310, 290, 330]    # Loja C
])
display(vendas_filiais)

array([[200., 220.,  nan, 250.],
       [150., 180., 160., 190.],
       [300., 310., 290., 330.]])

### Passo 2: Calcule o total de peças vendidas por cada loja (agregando pelas linhas).

In [6]:
total_pecas_por_loja = np.nansum(vendas_filiais, axis=1)
display(total_pecas_por_loja)

array([ 670.,  680., 1230.])

### Passo 3: Calcule a média diária geral da rede, ignorando valores `nan`.

In [7]:
media_diaria_geral = np.nanmean(vendas_filiais)
display(f"Média diária geral da rede (ignorando NaN): {media_diaria_geral:.2f}")

'Média diária geral da rede (ignorando NaN): 234.55'

### Passo 4: Crie uma nova matriz condicional usando `np.where()` para 'Meta Atingida' ou 'Abaixo'.

In [8]:
meta_diaria = 200
status_vendas = np.where(vendas_filiais >= meta_diaria, 'Meta Atingida', 'Abaixo')
display(status_vendas)

array([['Meta Atingida', 'Meta Atingida', 'Abaixo', 'Meta Atingida'],
       ['Abaixo', 'Abaixo', 'Abaixo', 'Abaixo'],
       ['Meta Atingida', 'Meta Atingida', 'Meta Atingida',
        'Meta Atingida']], dtype='<U13')

## Nível 3: Avançado — Categorização e Destaques de Marketing

### Passo 1: Crie uma amostra com 50 vendas sorteadas entre as opções de categoria.

In [9]:
rng = np.random.default_rng(seed=42) # Usando uma semente fixa para reprodutibilidade
categorias_venda = ['Eletrônicos', 'Roupas', 'Casa']
amostra_vendas = rng.choice(categorias_venda, size=50)
display(amostra_vendas)

array(['Eletrônicos', 'Casa', 'Roupas', 'Roupas', 'Roupas', 'Casa',
       'Eletrônicos', 'Casa', 'Eletrônicos', 'Eletrônicos', 'Roupas',
       'Casa', 'Casa', 'Casa', 'Casa', 'Casa', 'Roupas', 'Eletrônicos',
       'Casa', 'Roupas', 'Roupas', 'Roupas', 'Eletrônicos', 'Casa',
       'Casa', 'Roupas', 'Roupas', 'Casa', 'Roupas', 'Roupas', 'Roupas',
       'Eletrônicos', 'Eletrônicos', 'Roupas', 'Casa', 'Eletrônicos',
       'Casa', 'Casa', 'Eletrônicos', 'Roupas', 'Eletrônicos', 'Casa',
       'Casa', 'Roupas', 'Eletrônicos', 'Casa', 'Roupas', 'Casa', 'Casa',
       'Casa'], dtype='<U11')

### Passo 2: Determine o volume de vendas de cada departamento usando `np.unique`.

In [10]:
departamentos, contagens = np.unique(amostra_vendas, return_counts=True)
display(f"Departamentos: {departamentos}")
display(f"Contagens: {contagens}")

"Departamentos: ['Casa' 'Eletrônicos' 'Roupas']"

'Contagens: [21 12 17]'

### Passo 3: Identifique a campanha campeã pelo índice do maior valor.

In [11]:
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])
indice_campea = np.argmax(faturamento_campanhas)
valor_campea = faturamento_campanhas[indice_campea]

display(f"Faturamento das campanhas: {faturamento_campanhas}")
display(f"Índice da campanha campeã: {indice_campea}")
display(f"Faturamento da campanha campeã: R$ {valor_campea:.2f}")

'Faturamento das campanhas: [12000 45000 23000 89000 31000]'

'Índice da campanha campeã: 3'

'Faturamento da campanha campeã: R$ 89000.00'