<a href="https://colab.research.google.com/github/Blenkzx/LINGUAGENS-DE-PROGRAMA-O/blob/main/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade Prática: Organização e Transformação de Dados com NumPy

In [1]:
import numpy as np

## Nível 1: Básico — Geração de Sequências e Tipagem de Dados

O foco desta etapa é criar e padronizar vetores de dados gerados automaticamente.

### Passo 1: Crie um array representando os 30 dias de um mês de faturamento utilizando a função `np.arange(1, 31)`.

In [2]:
dias_faturamento = np.arange(1, 31)
display(dias_faturamento)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

### Passo 2: Simule 5 metas de vendas igualmente espaçadas entre R$ 20.000 e R$ 30.000 para uma equipe ao longo da semana utilizando a função `np.linspace(20000, 30000, 5)`.

In [3]:
metas_vendas = np.linspace(20000, 30000, 5)
display(metas_vendas)

array([20000., 22500., 25000., 27500., 30000.])

### Passo 3: O sistema de logística exportou a contagem de estoque físico como números decimais (ex: `np.array([10.5, 20.1, 30.9])`). Converta este array diretamente para números inteiros utilizando o método `.astype(int)`.

In [4]:
estoque_decimal = np.array([10.5, 20.1, 30.9])
estoque_inteiro = estoque_decimal.astype(int)
display(estoque_inteiro)

array([10, 20, 30])

### Passo 4: A partir do array de dias do mês criado no Passo 1, capture os últimos 5 dias e inverta a ordem (do mais recente para o mais antigo) através do fatiamento com passo negativo `[::-1]`.

In [5]:
ultimos_5_dias_invertidos = dias_faturamento[-5:][::-1]
display(ultimos_5_dias_invertidos)

array([30, 29, 28, 27, 26])

## Nível 2: Intermediário — Redimensionamento e Proteção de Dados

Aqui, o objetivo é manipular o formato (shape) das matrizes e entender como o Python gerencia a memória durante o fatiamento.

### Passo 1: Você recebeu um array unidimensional com o total de visitas de um portal em 12 meses. Utilize o método `.reshape(4, 3)` para reorganizar automaticamente esses elementos em uma matriz de 4 trimestres (4 linhas e 3 colunas).

In [6]:
visitas_12_meses = np.array([1200, 1500, 1300, 1600, 1800, 1700, 2000, 2100, 1900, 2200, 2400, 2300])
matriz_trimestres = visitas_12_meses.reshape(4, 3)
display(matriz_trimestres)

array([[1200, 1500, 1300],
       [1600, 1800, 1700],
       [2000, 2100, 1900],
       [2200, 2400, 2300]])

### Passo 2: A equipe de marketing enviou os dados do primeiro semestre e a equipe comercial enviou os do segundo semestre. Combine essas duas matrizes empilhando-as verticalmente com a função `np.vstack()`.

In [7]:
primeiro_semestre = np.array([[10, 20, 30],
                            [40, 50, 60]])
segundo_semestre = np.array([[70, 80, 90],
                           [100, 110, 120]])
dados_anuais = np.vstack((primeiro_semestre, segundo_semestre))
display(dados_anuais)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

### Passo 3: Extraia apenas o primeiro trimestre da matriz para criar um cenário de projeção no Google Colab. Para evitar a "pegadinha" onde alterar a nova fatia modifica o array original por acidente, utilize o método `.copy()` no momento do fatiamento.

In [8]:
primeiro_trimestre_projecao = matriz_trimestres[0, :].copy()
display(primeiro_trimestre_projecao)

# Testando a proteção: alterando a cópia não afeta o original
primeiro_trimestre_projecao[0] = 9999
display(primeiro_trimestre_projecao)
display(matriz_trimestres)

array([1200, 1500, 1300])

array([9999, 1500, 1300])

array([[1200, 1500, 1300],
       [1600, 1800, 1700],
       [2000, 2100, 1900],
       [2200, 2400, 2300]])

### Passo 4: Para exportar os dados estruturados de volta para um formato de relatório corrido, utilize o método `ravel()` para achatar a matriz bidimensional de volta em um array 1D.

In [9]:
dados_relatorio = dados_anuais.ravel()
display(dados_relatorio)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

## Nível 3: Avançado — Ranking, Broadcasting e Resolução de Sistemas

Esta etapa explora álgebra linear e manipulação de dimensões para análise de cenários.

### Passo 1: Você possui as seguintes pontuações de alunos em uma avaliação de pensamento computacional: `np.array([85, 92, 78, 95, 88])`. Em vez de apenas ordenar os valores, utilize `np.argsort()` para obter os índices dessa ordenação, permitindo descobrir rapidamente a posição de cada aluno no ranking geral.

In [10]:
pontuacoes_alunos = np.array([85, 92, 78, 95, 88])
indices_ordenados = np.argsort(pontuacoes_alunos)
display(f"Pontuações originais: {pontuacoes_alunos}")
display(f"Índices para ordenação (do menor para o maior): {indices_ordenados}")

# Para ver o ranking (do maior para o menor, ou seja, os alunos com maiores pontuações)
# Podemos inverter os índices para ter o ranking do melhor para o pior
ranking_alunos = np.argsort(pontuacoes_alunos)[::-1]
display(f"Índices do ranking (do maior para o menor): {ranking_alunos}")
display(f"Pontuações em ordem de ranking: {pontuacoes_alunos[ranking_alunos]}")

'Pontuações originais: [85 92 78 95 88]'

'Índices para ordenação (do menor para o maior): [2 0 4 1 3]'

'Índices do ranking (do maior para o menor): [3 1 4 0 2]'

'Pontuações em ordem de ranking: [95 92 88 85 78]'

### Passo 2: Você possui um vetor contendo preços base em formato de linha. Insira uma nova dimensão neste vetor utilizando `np.newaxis` para transformá-lo estruturalmente em uma coluna. Isso prepara a matriz para cruzar e aplicar múltiplos percentuais de desconto simultaneamente via regras de broadcasting.

In [11]:
precos_base = np.array([100, 200, 300])

# Transforma o vetor de linha em vetor coluna
precos_coluna = precos_base[:, np.newaxis]
display(f"Preços base (vetor original): {precos_base}")
display(f"Shape do vetor original: {precos_base.shape}")
display(f"Preços (vetor coluna):\n{precos_coluna}")
display(f"Shape do vetor coluna: {precos_coluna.shape}")

# Exemplo de aplicação de broadcasting com descontos
percentuais_desconto = np.array([0.1, 0.2, 0.3]) # 10%, 20%, 30% de desconto
precos_com_desconto = precos_coluna * (1 - percentuais_desconto)
display(f"Tabela de preços com diferentes descontos:\n{precos_com_desconto}")

'Preços base (vetor original): [100 200 300]'

'Shape do vetor original: (3,)'

'Preços (vetor coluna):\n[[100]\n [200]\n [300]]'

'Shape do vetor coluna: (3, 1)'

'Tabela de preços com diferentes descontos:\n[[ 90.  80.  70.]\n [180. 160. 140.]\n [270. 240. 210.]]'

Passo 3: Descubra o custo unitário exato de dois recursos de hardware para um laboratório. O projeto A usou 2 placas robóticas e 1 sensor, custando 500 no total. O projeto B usou 1 placa robótica e devolveu 1 sensor (estorno), custando 100 no total. Crie a matriz de coeficientes A e o vetor de resultados b, aplicando a função `np.linalg.solve(A, b)` para encontrar os valores individuais das peças sem realizar o cálculo manual.

In [12]:
# Definir a matriz de coeficientes A
# A = [[quantidade_placas_projA, quantidade_sensores_projA],
#      [quantidade_placas_projB, quantidade_sensores_projB]]
# Onde: x = custo da placa robótica, y = custo do sensor
# Equações:
# 2x + 1y = 500
# 1x - 1y = 100

A = np.array([[2, 1],
              [1, -1]])

# Definir o vetor de resultados b
b = np.array([500, 100])

# Resolver o sistema de equações
custos_unitarios = np.linalg.solve(A, b)

display(f"Matriz de coeficientes A:\n{A}")
display(f"Vetor de resultados b:\n{b}")
display(f"Custos unitários (Placa Robótica, Sensor): {custos_unitarios}")
display(f"Custo unitário da Placa Robótica: R$ {custos_unitarios[0]:.2f}")
display(f"Custo unitário do Sensor: R$ {custos_unitarios[1]:.2f}")

'Matriz de coeficientes A:\n[[ 2  1]\n [ 1 -1]]'

'Vetor de resultados b:\n[500 100]'

'Custos unitários (Placa Robótica, Sensor): [200. 100.]'

'Custo unitário da Placa Robótica: R$ 200.00'

'Custo unitário do Sensor: R$ 100.00'